# Generated by Django 4.2.5 on 2023-10-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drinks', '0002_drink_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('experience_years', models.PositiveIntegerField()),
                ('drinks', models.ManyToManyField(blank=True, related_name='bartenders', to='drinks.drink')),
            ],
        ),
    ]
